/**
 * TypeScript interfaces for extended dashboard data schemas
 * 
 * These interfaces define the structure of JSON data files that will be
 * generated by the Python backend for advanced dashboard visualizations.
 * 
 * Requirements: 11.1-11.5, 5.1, 6.1, 7.1, 8.1, 9.1
 */

// ── ML Models Extended ────────────────────────────────────────────────────────

export interface MLModelPrediction {
  date: string;
  fragility_score: number;
  regime: string;
  confidence: number;
}

export interface ROCPoint {
  fpr: number; // False Positive Rate
  tpr: number; // True Positive Rate
}

export interface ModelPerformanceMetrics {
  accuracy: number;
  precision: number;
  recall: number;
  f1_score: number;
  roc_auc: number;
  roc_curve: ROCPoint[];
}

export interface MLModelsExtendedData {
  metadata: {
    generated_at: string;
    models: string[]; // ['GradientBoosting', 'LSTM', 'SVR', 'ElasticNet', 'Ensemble']
  };
  predictions: {
    [modelId: string]: MLModelPrediction[];
  };
  performance: {
    [modelId: string]: ModelPerformanceMetrics;
  };
}

// ── Regime Transitions ────────────────────────────────────────────────────────

export interface RegimeTransitionSnapshot {
  date: string;
  matrix: number[][]; // 3x3 transition probability matrix
  current_regime: string;
}

export interface RegimeTransitionsData {
  metadata: {
    regimes: string[]; // ['normal', 'stressed', 'crisis']
  };
  transitions: RegimeTransitionSnapshot[];
}

// ── DTW Similarity ────────────────────────────────────────────────────────────

export interface SimilarPeriod {
  date: string;
  score: number; // 0-1, higher = more similar
  features_matched: string[];
}

export interface DTWSimilaritySnapshot {
  reference_date: string;
  similar_periods: SimilarPeriod[];
}

export interface DTWSimilarityData {
  metadata: {
    window_size: number; // days for DTW comparison
    feature_set: string[];
  };
  similarities: DTWSimilaritySnapshot[];
}

// ── Correlation Networks ──────────────────────────────────────────────────────

export interface NetworkNode {
  id: string;
  label: string;
}

export interface NetworkEdge {
  source: string;
  target: string;
  weight: number; // correlation strength
}

export interface NetworkMetrics {
  density: number;
  clustering_coefficient: number;
  avg_degree: number;
}

export interface NetworkSnapshot {
  date: string;
  nodes: NetworkNode[];
  edges: NetworkEdge[];
  metrics: NetworkMetrics;
}

export interface CorrelationNetworksData {
  metadata: {
    indices: string[];
    threshold: number; // correlation threshold for edge creation
  };
  snapshots: NetworkSnapshot[];
}

// ── Volatility Clusters ───────────────────────────────────────────────────────

export interface VolatilityDataPoint {
  date: string;
  volatility: number;
}

export interface VolatilityCluster {
  id: number;
  start_date: string;
  end_date: string;
  intensity: number;
  duration_days: number;
}

export interface VolatilityClusteringData {
  metadata: {
    clustering_algorithm: string; // e.g., 'DBSCAN'
    min_cluster_duration: number; // days
  };
  time_series: VolatilityDataPoint[];
  clusters: VolatilityCluster[];
}

// ── Lead Time Stats ───────────────────────────────────────────────────────────

export interface CrisisPrediction {
  crisis_date: string;
  prediction_date: string;
  lead_time_days: number;
  model_id: string;
  was_actionable: boolean;
}

export interface LeadTimeSummary {
  mean_lead_time: number;
  median_lead_time: number;
  min_lead_time: number;
  max_lead_time: number;
  actionable_percentage: number;
}

export interface LeadTimeStatsData {
  metadata: {
    crisis_threshold: number; // fragility score threshold
    actionable_lead_time: number; // days
  };
  predictions: CrisisPrediction[];
  summary: {
    [modelId: string]: LeadTimeSummary;
  };
}
